all: clean
	@ cd /home/utnso/tp-2014-2c-los-envirusaos/Proceso_Consola/Debug; make all ; cd .. ; cd .. ;
	@ cd /home/utnso/tp-2014-2c-los-envirusaos/Proceso_CPU/Debug; make all ; cd .. ; cd .. ;
	@ cd /home/utnso/tp-2014-2c-los-envirusaos/Proceso_Kernel/Debug; make all ; cd .. ; cd .. ;
	@ cd /home/utnso/tp-2014-2c-los-envirusaos/Proceso_MSP/Debug; make all ; cd .. ; cd .. ;

clean:
	@ cd /home/utnso/tp-2014-2c-los-envirusaos/Proceso_Consola/Debug; make clean ; cd .. ; cd .. ;
	@ cd /home/utnso/tp-2014-2c-los-envirusaos/Proceso_CPU/Debug; make clean ; cd .. ; cd .. ;
	@ cd /home/utnso/tp-2014-2c-los-envirusaos/Proceso_Kernel/Debug; make clean ; cd .. ; cd .. ;
	@ cd /home/utnso/tp-2014-2c-los-envirusaos/Proceso_MSP/Debug; make clean ; cd .. ; cd .. ;


